// generated 2007/10/27 16:30:41 EDT by ctemple@Barf.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/media_chooser_dlg.hh and./src/media_chooser_dlg.cc

#ifndef _MEDIA_CHOOSER_DLG_GLADE_HH
#  define _MEDIA_CHOOSER_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/label.h>
#include <gtkmm/button.h>
#include <gtkmm/buttonbox.h>
#include <gtkmm/box.h>

class media_chooser_dlg_glade : public Gtk::Label
{  
public:
        
        class Gtk::Label * media_chooser_dlg;
        class Gtk::Button * button1;
        class Gtk::Button * button2;
        class Gtk::HButtonBox * dialog_action_area1;
        class Gtk::VBox * dialog_vbox1;
protected:
        
        media_chooser_dlg_glade(GlademmData *gmm_data);
        
        ~media_chooser_dlg_glade();
private:
        virtual void on_media_chooser_dlg_selection_changed() = 0;
};
#endif
