// generated 2007/10/31 22:10:50 EDT by jmorey@jmorey-desktop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/admin_dlg.hh and./src/admin_dlg.cc

#ifndef _ADMIN_DLG_GLADE_HH
#  define _ADMIN_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/entry.h>
#include <gtkmm/separator.h>
#include <gtkmm/button.h>
#include <gtkmm/image.h>
#include <gtkmm/box.h>
#include <gtkmm/viewport.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/alignment.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/fixed.h>

class admin_dlg_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * admin_dlg;
        class Gtk::Entry * pssword_confirm_edit_box;
        class Gtk::Entry * sec_ques_edit_box;
        class Gtk::Entry * password_edit_box;
        class Gtk::Entry * sec_ans_edit_box;
        class Gtk::HSeparator * hseparator3;
        class Gtk::Button * logout_button;
        class Gtk::Button * admin_settings_button;
        class Gtk::Button * add_user_button;
        class Gtk::Button * remove_user_button;
        class Gtk::Button * edit_user_button;
        class Gtk::HSeparator * hseparator2;
        class Gtk::Image * image42;
        class Gtk::Button * button33;
        class Gtk::Image * image43;
        class Gtk::Button * button4;
        class Gtk::Image * image44;
        class Gtk::Button * button5;
        class Gtk::Image * image45;
        class Gtk::Button * button6;
        class Gtk::Image * image46;
        class Gtk::Button * button7;
        class Gtk::Image * image47;
        class Gtk::Button * button8;
        class Gtk::Image * image48;
        class Gtk::Button * button9;
        class Gtk::Image * image49;
        class Gtk::Button * button10;
        class Gtk::Image * image50;
        class Gtk::Button * button11;
        class Gtk::Image * image51;
        class Gtk::Button * button12;
        class Gtk::Image * image52;
        class Gtk::Button * button13;
        class Gtk::Image * image53;
        class Gtk::Button * button14;
        class Gtk::Image * image54;
        class Gtk::Button * button15;
        class Gtk::Image * image55;
        class Gtk::Button * button16;
        class Gtk::Image * image71;
        class Gtk::Button * button17;
        class Gtk::Image * image70;
        class Gtk::Button * button18;
        class Gtk::Image * image69;
        class Gtk::Button * button19;
        class Gtk::Image * image68;
        class Gtk::Button * button20;
        class Gtk::Image * image67;
        class Gtk::Button * button21;
        class Gtk::Image * image66;
        class Gtk::Button * button22;
        class Gtk::Image * image65;
        class Gtk::Button * button23;
        class Gtk::Image * image64;
        class Gtk::Button * button24;
        class Gtk::Image * image63;
        class Gtk::Button * button25;
        class Gtk::Image * image62;
        class Gtk::Button * button32;
        class Gtk::Image * image61;
        class Gtk::Button * button31;
        class Gtk::HBox * hbox5;
        class Gtk::Viewport * viewport1;
        class Gtk::ScrolledWindow * scrolledwindow1;
        class Gtk::Alignment * alignment6;
        class Gtk::Label * icon_select_frame_label;
        class Gtk::Frame * frame2;
        class Gtk::VSeparator * vseparator1;
        class Gtk::Entry * username_edit_box;
        class Gtk::Label * user_name_label;
        class Gtk::Label * password_label;
        class Gtk::Label * confirm_password_label;
        class Gtk::Label * seq_ques_label;
        class Gtk::Label * sec_ans_label;
        class Gtk::Button * accept_changes_button;
        class Gtk::CheckButton * hide_confirm_checkbox;
        class Gtk::CheckButton * hide_password_checkbox;
        class Gtk::CheckButton * hide_sec_ques_checkbox;
        class Gtk::CheckButton * hide_sec_ans_checkbox;
        class Gtk::Fixed * fixed9;
        class Gtk::VBox * vbox6;
        class Gtk::VBox * vbox5;
        class Gtk::Alignment * alignment5;
        class Gtk::Frame * frame1;
        class Gtk::CheckButton * pg_checkbox;
        class Gtk::CheckButton * pg13_checkbox;
        class Gtk::CheckButton * g_checkbox;
        class Gtk::CheckButton * nc17_checkbox;
        class Gtk::CheckButton * x_checkbox;
        class Gtk::CheckButton * r_checkbox;
        class Gtk::CheckButton * unknown_checkbox;
        class Gtk::CheckButton * nr_checkbox;
        class Gtk::Button * screen_movies_button;
        class Gtk::Image * admin_icon;
        class Gtk::Label * user_label;
        class Gtk::Fixed * fixed8;
protected:
        
        admin_dlg_glade();
        
        ~admin_dlg_glade();
private:
        virtual bool on_pssword_confirm_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_sec_ques_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_password_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_sec_ans_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_logout_button_clicked() = 0;
        virtual void on_admin_settings_button_clicked() = 0;
        virtual void on_add_user_button_clicked() = 0;
        virtual void on_remove_user_button_clicked() = 0;
        virtual void on_edit_user_button_clicked() = 0;
        virtual bool on_username_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_hide_confirm_checkbox_toggled() = 0;
        virtual void on_hide_password_checkbox_toggled() = 0;
        virtual void on_hide_sec_ques_checkbox_toggled() = 0;
        virtual void on_hide_sec_ans_checkbox_toggled() = 0;
        virtual void on_pg_checkbox_toggled() = 0;
        virtual void on_pg13_checkbox_toggled() = 0;
        virtual void on_g_checkbox_toggled() = 0;
        virtual void on_nc17_checkbox_toggled() = 0;
        virtual void on_x_checkbox_toggled() = 0;
        virtual void on_r_checkbox_toggled() = 0;
        virtual void on_unknown_checkbox_toggled() = 0;
        virtual void on_nr_checkbox_toggled() = 0;
        virtual void on_screen_movies_button_clicked() = 0;
};
#endif
