// generated 2007/11/4 15:51:41 EST by ctemple@Barf.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/playlist_dlg.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "playlist_dlg_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>

playlist_dlg_glade::playlist_dlg_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  playlist_dlg = this;
   gmm_data = new GlademmData(get_accel_group());
   vbox4 = Gtk::manage(new class Gtk::VBox(false, 0));
   playlist_dlg->set_title(_("Playlist"));
   playlist_dlg->set_modal(false);
   playlist_dlg->property_window_position().set_value(Gtk::WIN_POS_NONE);
   playlist_dlg->set_resizable(true);
   playlist_dlg->property_destroy_with_parent().set_value(false);
   playlist_dlg->add(*vbox4);
   vbox4->show();
   playlist_dlg->show();
}

playlist_dlg_glade::~playlist_dlg_glade()
{  delete gmm_data;
}
