// generated 2007/10/23 20:56:44 EDT by ctemple@Barf.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/playlist_dlg.hh and./src/playlist_dlg.cc

#ifndef _PLAYLIST_DLG_GLADE_HH
#  define _PLAYLIST_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/box.h>

class playlist_dlg_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * playlist_dlg;
        class Gtk::CheckButton * checkbutton1;
        class Gtk::VBox * vbox4;
protected:
        
        playlist_dlg_glade();
        
        ~playlist_dlg_glade();
};
#endif
