// generated 2007/11/6 23:15:33 EST by jmorey@jmorey-desktop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/admin_dlg.hh and./src/admin_dlg.cc

#ifndef _ADMIN_DLG_GLADE_HH
#  define _ADMIN_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/entry.h>
#include <gtkmm/separator.h>
#include <gtkmm/button.h>
#include <gtkmm/box.h>
#include <gtkmm/viewport.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/alignment.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/image.h>
#include <gtkmm/checkbutton.h>
#include <gtkmm/fixed.h>
#include <gtkmm/radiobutton.h>

class admin_dlg_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * admin_dlg;
        class Gtk::Entry * pssword_confirm_edit_box;
        class Gtk::Entry * sec_ques_edit_box;
        class Gtk::Entry * password_edit_box;
        class Gtk::Entry * sec_ans_edit_box;
        class Gtk::HSeparator * hseparator3;
        class Gtk::Button * logout_button;
        class Gtk::Button * admin_settings_button;
        class Gtk::Button * remove_user_button;
        class Gtk::Button * edit_user_button;
        class Gtk::HBox * hbox5;
        class Gtk::Viewport * viewport1;
        class Gtk::ScrolledWindow * scrolledwindow1;
        class Gtk::Alignment * alignment6;
        class Gtk::Label * icon_select_frame_label;
        class Gtk::Frame * frame2;
        class Gtk::VSeparator * vseparator1;
        class Gtk::Image * admin_icon;
        class Gtk::Label * user_label;
        class Gtk::Button * add_user_button;
        class Gtk::HSeparator * hseparator2;
        class Gtk::Entry * username_edit_box;
        class Gtk::Button * accept_changes_button;
        class Gtk::CheckButton * hide_confirm_checkbox;
        class Gtk::CheckButton * hide_password_checkbox;
        class Gtk::CheckButton * hide_sec_ques_checkbox;
        class Gtk::CheckButton * hide_sec_ans_checkbox;
        class Gtk::Label * sec_ans_label;
        class Gtk::Label * sec_ques_label;
        class Gtk::Label * confirm_password_label;
        class Gtk::Label * password_label;
        class Gtk::Label * user_name_label;
        class Gtk::Label * error_label;
        class Gtk::Fixed * fixed9;
        class Gtk::VBox * vbox6;
        class Gtk::VBox * vbox5;
        class Gtk::Alignment * alignment5;
        class Gtk::Frame * frame1;
        class Gtk::RadioButton * g_radio_button;
        class Gtk::RadioButton * pg_radio_button;
        class Gtk::RadioButton * pg13_radio_button;
        class Gtk::RadioButton * nc17_radio_button;
        class Gtk::RadioButton * r_radio_button;
        class Gtk::RadioButton * x_radio_button;
        class Gtk::CheckButton * nr_checkbox;
        class Gtk::Button * screen_movies_button;
        class Gtk::VBox * vbox7;
        class Gtk::Alignment * alignment7;
        class Gtk::Label * user_level_label;
        class Gtk::Frame * frame3;
        class Gtk::Fixed * fixed8;
		virtual void onIconButtonClicked() = 0;
protected:
        
        admin_dlg_glade();
        
        ~admin_dlg_glade();
private:
        virtual bool on_pssword_confirm_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_sec_ques_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_password_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_sec_ans_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_logout_button_clicked() = 0;
        virtual void on_admin_settings_button_clicked() = 0;
        virtual void on_remove_user_button_clicked() = 0;
        virtual void on_edit_user_button_clicked() = 0;
        virtual void on_add_user_button_clicked() = 0;
        virtual bool on_username_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_accept_changes_button_clicked() = 0;
        virtual void on_hide_confirm_checkbox_toggled() = 0;
        virtual void on_hide_password_checkbox_toggled() = 0;
        virtual void on_hide_sec_ques_checkbox_toggled() = 0;
        virtual void on_hide_sec_ans_checkbox_toggled() = 0;
        virtual void on_screen_movies_button_clicked() = 0;
};
#endif
