// generated 2007/12/6 18:26:41 EST by ctemple@Barf.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/DiscRating.hh and./src/DiscRating.cc

#ifndef _DISCRATING_GLADE_HH
#  define _DISCRATING_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/image.h>
#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/alignment.h>
#include <gtkmm/button.h>
#include <gtkmm/fixed.h>

class DiscRating_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * DiscRating;
        class Gtk::RadioButton * gButton;
        class Gtk::RadioButton * pgButton;
        class Gtk::RadioButton * nc17Button;
        class Gtk::RadioButton * rButton;
        class Gtk::RadioButton * pg13Button;
        class Gtk::Image * image17;
        class Gtk::Label * label15;
        class Gtk::HBox * hbox10;
        class Gtk::Alignment * alignment12;
        class Gtk::Button * saveButton;
        class Gtk::RadioButton * allButton;
        class Gtk::Fixed * fixed10;
protected:
        
        DiscRating_glade();
        
        ~DiscRating_glade();
private:
        virtual void on_saveButton_clicked() = 0;
};
#endif
