// generated 2007/10/27 16:30:41 EDT by ctemple@Barf.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/media_chooser_dlg.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "media_chooser_dlg_glade.hh"

media_chooser_dlg_glade::media_chooser_dlg_glade(GlademmData *gmm_data
)
{  media_chooser_dlg = this;
   button1 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-cancel")));
   button2 = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-open")));
   dialog_action_area1 = Gtk::manage(new class Gtk::HButtonBox(Gtk::BUTTONBOX_END, 0));
   dialog_vbox1 = Gtk::manage(new class Gtk::VBox(false, 24));
   button1->set_flags(Gtk::CAN_FOCUS);
   button1->set_flags(Gtk::CAN_DEFAULT);
   button1->set_relief(Gtk::RELIEF_NORMAL);
   button2->set_flags(Gtk::CAN_FOCUS);
   button2->set_flags(Gtk::CAN_DEFAULT);
   button2->set_relief(Gtk::RELIEF_NORMAL);
   dialog_action_area1->property_layout_style().set_value(Gtk::BUTTONBOX_END);
   dialog_vbox1->set_homogeneous(false);
   dialog_vbox1->set_spacing(24);
   dialog_vbox1->pack_start(*dialog_action_area1, Gtk::PACK_SHRINK, 0);
   button1->show();
   button2->show();
   dialog_action_area1->show();
   dialog_vbox1->show();
   media_chooser_dlg->show();
   media_chooser_dlg->signal_selection_changed().connect(SigC::slot(*this, &media_chooser_dlg_glade::on_media_chooser_dlg_selection_changed), false);
   button2->grab_default();
}

media_chooser_dlg_glade::~media_chooser_dlg_glade()
{  
}
