// generated 2007/10/15 12:07:33 EDT by jmorey@jmorey-desktop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/jmorey/Projects/DigitalParent/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/psswrd_prompt_dlg.hh and./src/psswrd_prompt_dlg.cc

#ifndef _PSSWRD_PROMPT_DLG_GLADE_HH
#  define _PSSWRD_PROMPT_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/entry.h>
#include <gtkmm/textview.h>
#include <gtkmm/drawingarea.h>
#include <gtkmm/button.h>
#include <gtkmm/fixed.h>

class psswrd_prompt_dlg_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * psswrd_prompt_dlg;
        class Gtk::Entry * psswrd_edit_box;
        class Gtk::TextView * login_text_box;
        class Gtk::DrawingArea * drawingarea1;
        class Gtk::DrawingArea * drawingarea5;
        class Gtk::Button * login_icon_button;
        class Gtk::Fixed * fixed2;
protected:
        
        psswrd_prompt_dlg_glade();
        
        ~psswrd_prompt_dlg_glade();
private:
        virtual void on_psswrd_edit_box_editing_done() = 0;
        virtual void on_login_icon_button_clicked() = 0;
};
#endif
