// generated 2007/11/23 15:34:30 EST by jmorey@jmorey-desktop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/welcome_dlg.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "welcome_dlg_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include <gdkmm/pixbufloader.h>

static const unsigned char no_user_png_data[] = 
{       	137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,
	0,0,0,89,0,0,0,89,8,2,0,0,0,218,105,31,
	248,0,0,0,4,103,65,77,65,0,0,177,143,11,252,97,
	5,0,0,2,5,73,68,65,84,120,94,237,156,237,118,131,
	32,16,68,211,55,247,209,250,104,77,14,61,72,217,101,25,
	173,96,140,215,127,241,3,97,152,185,2,49,249,90,150,229,
	193,150,20,120,106,193,150,20,248,213,226,251,246,27,90,172,
	22,64,11,180,240,128,128,47,240,5,190,136,31,149,100,132,
	140,144,17,50,162,14,168,225,5,188,128,23,240,2,94,168,
	10,192,11,120,1,47,212,180,48,190,128,23,240,2,94,192,
	11,85,1,120,1,47,224,133,154,150,33,227,139,252,69,117,
	174,133,221,163,86,112,226,121,104,49,152,157,248,98,21,184,
	171,69,245,182,71,153,131,242,144,27,177,116,194,136,232,156,
	144,145,74,169,178,109,246,141,152,212,230,64,187,3,69,57,
	83,139,170,123,93,141,210,57,115,208,123,130,22,173,126,110,
	189,38,245,225,90,88,231,199,13,190,176,47,108,207,91,40,
	84,114,184,92,200,87,93,91,139,24,120,226,115,36,3,229,
	242,90,28,72,248,57,69,13,97,231,156,170,31,126,23,180,
	24,60,6,63,188,199,230,20,136,47,240,133,231,52,124,129,
	47,186,190,232,206,181,231,48,172,172,134,56,202,10,78,19,
	75,120,54,237,79,70,208,98,253,205,196,155,104,225,46,237,
	196,150,156,237,139,216,186,238,50,76,44,110,119,229,198,78,
	94,255,115,73,86,179,44,164,148,120,67,70,148,245,5,59,
	233,106,41,168,148,86,105,161,92,18,87,192,157,64,103,57,
	246,104,97,167,219,226,146,84,224,172,174,100,129,71,244,67,
	65,61,183,177,51,46,200,93,128,40,119,230,26,87,201,215,
	173,228,154,60,205,235,183,118,134,187,104,48,220,23,214,150,
	214,86,173,44,4,251,247,29,138,159,175,245,184,211,205,164,
	94,123,87,111,219,111,110,110,211,181,138,46,129,149,118,240,
	34,221,180,206,72,224,243,216,135,113,47,185,90,40,109,222,
	97,254,110,61,91,62,245,181,168,242,124,159,143,204,205,214,
	190,70,11,180,240,146,143,47,240,5,190,136,159,137,100,132,
	140,144,17,50,162,142,156,225,5,188,128,23,240,2,94,168,
	10,192,11,120,1,47,212,180,48,190,128,23,240,2,94,192,
	11,85,1,120,1,47,224,133,154,22,198,23,240,2,94,192,
	139,237,188,120,253,37,244,237,183,31,231,54,55,164,158,120,
	155,253,0,0,0,0,73,69,78,68,174,66,96,130,

};

welcome_dlg_glade::welcome_dlg_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  welcome_dlg = this;
   gmm_data = new GlademmData(get_accel_group());
   label7 = Gtk::manage(new class Gtk::Label(_("\n"
		"Before you can begin using Digital Parent,\n"
		"you will need to set up an administrative\n"
		"account.  Create a password with 5-16 char-\n"
		"acters and a secret question and answer \n"
		"with 1-16 characters.  These are case \n"
		"sensitive.  Write down your password in a\n"
		"safe place and then click next to continue.\n"
		"Tux, the penguin in the picture, will be on\n"
		"your login button when you want to login\n"
		"as administrator.\n"
		"\n"
		"")));
   
   Glib::RefPtr<Gdk::PixbufLoader> _Tux_image_loader=Gdk::PixbufLoader::create();
   _Tux_image_loader->write(no_user_png_data, sizeof no_user_png_data);
   _Tux_image_loader->close();
   Tux_image = Gtk::manage(new class Gtk::Image(_Tux_image_loader->get_pixbuf()));
   _Tux_image_loader=Glib::RefPtr<Gdk::PixbufLoader>();
   fixed7 = Gtk::manage(new class Gtk::Fixed());
   init_password_edit_box = Gtk::manage(new class Gtk::Entry());
   init_password_label = Gtk::manage(new class Gtk::Label(_("Enter Password")));
   repeat_password_label = Gtk::manage(new class Gtk::Label(_("Repeat Password")));
   repeat_password_edit_box = Gtk::manage(new class Gtk::Entry());
   secret_question_label = Gtk::manage(new class Gtk::Label(_("Secret Question")));
   secret_answer_label = Gtk::manage(new class Gtk::Label(_("Secret Answer")));
   secret_q_edit_box = Gtk::manage(new class Gtk::Entry());
   secret_a_edit_box = Gtk::manage(new class Gtk::Entry());
   welcome_next_button = Gtk::manage(new class Gtk::Button(Gtk::StockID("gtk-media-next")));
   welcome_hint_label = Gtk::manage(new class Gtk::Label(_("")));
   fixed6 = Gtk::manage(new class Gtk::Fixed());
   vbox2 = Gtk::manage(new class Gtk::VBox(false, 0));
   label7->set_size_request(368,208);
   label7->set_alignment(0.5,0.5);
   label7->set_padding(0,0);
   label7->set_justify(Gtk::JUSTIFY_LEFT);
   label7->set_line_wrap(false);
   label7->set_use_markup(false);
   label7->set_selectable(false);
   Tux_image->set_size_request(152,152);
   Tux_image->set_alignment(0.5,0.5);
   Tux_image->set_padding(0,0);
   fixed7->put(*label7, 192, 0);
   fixed7->put(*Tux_image, 24, 24);
   init_password_edit_box->set_size_request(160,27);
   init_password_edit_box->set_flags(Gtk::CAN_FOCUS);
   init_password_edit_box->set_visibility(false);
   init_password_edit_box->set_editable(true);
   init_password_edit_box->set_max_length(16);
   init_password_edit_box->set_text(_(""));
   init_password_edit_box->set_has_frame(true);
   init_password_edit_box->set_activates_default(false);
   init_password_label->set_size_request(125,17);
   init_password_label->set_alignment(0.5,0.5);
   init_password_label->set_padding(0,0);
   init_password_label->set_justify(Gtk::JUSTIFY_CENTER);
   init_password_label->set_line_wrap(false);
   init_password_label->set_use_markup(false);
   init_password_label->set_selectable(false);
   repeat_password_label->set_size_request(125,17);
   repeat_password_label->set_alignment(0.5,0.5);
   repeat_password_label->set_padding(0,0);
   repeat_password_label->set_justify(Gtk::JUSTIFY_CENTER);
   repeat_password_label->set_line_wrap(false);
   repeat_password_label->set_use_markup(false);
   repeat_password_label->set_selectable(false);
   repeat_password_edit_box->set_size_request(160,27);
   repeat_password_edit_box->set_flags(Gtk::CAN_FOCUS);
   repeat_password_edit_box->set_visibility(false);
   repeat_password_edit_box->set_editable(true);
   repeat_password_edit_box->set_max_length(16);
   repeat_password_edit_box->set_text(_(""));
   repeat_password_edit_box->set_has_frame(true);
   repeat_password_edit_box->set_activates_default(false);
   secret_question_label->set_size_request(125,17);
   secret_question_label->set_alignment(0.5,0.5);
   secret_question_label->set_padding(0,0);
   secret_question_label->set_justify(Gtk::JUSTIFY_CENTER);
   secret_question_label->set_line_wrap(false);
   secret_question_label->set_use_markup(false);
   secret_question_label->set_selectable(false);
   secret_answer_label->set_size_request(125,17);
   secret_answer_label->set_alignment(0.5,0.5);
   secret_answer_label->set_padding(0,0);
   secret_answer_label->set_justify(Gtk::JUSTIFY_CENTER);
   secret_answer_label->set_line_wrap(false);
   secret_answer_label->set_use_markup(false);
   secret_answer_label->set_selectable(false);
   secret_q_edit_box->set_size_request(160,27);
   secret_q_edit_box->set_flags(Gtk::CAN_FOCUS);
   secret_q_edit_box->set_visibility(true);
   secret_q_edit_box->set_editable(true);
   secret_q_edit_box->set_max_length(16);
   secret_q_edit_box->set_text(_(""));
   secret_q_edit_box->set_has_frame(true);
   secret_q_edit_box->set_activates_default(false);
   secret_a_edit_box->set_size_request(160,27);
   secret_a_edit_box->set_flags(Gtk::CAN_FOCUS);
   secret_a_edit_box->set_visibility(true);
   secret_a_edit_box->set_editable(true);
   secret_a_edit_box->set_max_length(16);
   secret_a_edit_box->set_text(_(""));
   secret_a_edit_box->set_has_frame(true);
   secret_a_edit_box->set_activates_default(false);
   welcome_next_button->set_size_request(86,45);
   welcome_next_button->set_flags(Gtk::CAN_FOCUS);
   welcome_next_button->set_relief(Gtk::RELIEF_NORMAL);
   welcome_hint_label->set_size_request(200,72);
   welcome_hint_label->set_alignment(0.5,0.5);
   welcome_hint_label->set_padding(0,0);
   welcome_hint_label->set_justify(Gtk::JUSTIFY_LEFT);
   welcome_hint_label->set_line_wrap(true);
   welcome_hint_label->set_use_markup(false);
   welcome_hint_label->set_selectable(false);
   fixed6->put(*init_password_edit_box, 176, 16);
   fixed6->put(*init_password_label, 32, 24);
   fixed6->put(*repeat_password_label, 32, 64);
   fixed6->put(*repeat_password_edit_box, 176, 56);
   fixed6->put(*secret_question_label, 32, 104);
   fixed6->put(*secret_answer_label, 32, 144);
   fixed6->put(*secret_q_edit_box, 176, 96);
   fixed6->put(*secret_a_edit_box, 176, 136);
   fixed6->put(*welcome_next_button, 504, 128);
   fixed6->put(*welcome_hint_label, 368, 16);
   vbox2->pack_start(*fixed7);
   vbox2->pack_start(*fixed6, Gtk::PACK_SHRINK, 0);
   welcome_dlg->set_size_request(600,375);
   welcome_dlg->set_title(_("Welcome to Digital Parent"));
   welcome_dlg->set_default_size(600,450);
   welcome_dlg->set_modal(false);
   welcome_dlg->property_window_position().set_value(Gtk::WIN_POS_NONE);
   welcome_dlg->set_resizable(false);
   welcome_dlg->property_destroy_with_parent().set_value(false);
   welcome_dlg->add(*vbox2);
   label7->show();
   Tux_image->show();
   fixed7->show();
   init_password_edit_box->show();
   init_password_label->show();
   repeat_password_label->show();
   repeat_password_edit_box->show();
   secret_question_label->show();
   secret_answer_label->show();
   secret_q_edit_box->show();
   secret_a_edit_box->show();
   welcome_next_button->show();
   welcome_hint_label->show();
   fixed6->show();
   vbox2->show();
   welcome_dlg->show();
   repeat_password_edit_box->signal_key_press_event().connect(SigC::slot(*this, &welcome_dlg_glade::on_repeat_password_edit_box_key_press_event), false);
   secret_a_edit_box->signal_key_press_event().connect(SigC::slot(*this, &welcome_dlg_glade::on_secret_a_edit_box_key_press_event), false);
   welcome_next_button->signal_clicked().connect(SigC::slot(*this, &welcome_dlg_glade::on_welcome_next_button_clicked), false);
   welcome_dlg->signal_delete_event().connect(SigC::slot(*this, &welcome_dlg_glade::on_welcome_dlg_delete_event), false);
}

welcome_dlg_glade::~welcome_dlg_glade()
{  delete gmm_data;
}
