// generated 2007/11/23 11:44:13 EST by jmorey@jmorey-desktop.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /Projects/DP/DigitalParent.glade
// for gtk 2.10.11 and gtkmm 2.10.8
//
// Please modify the corresponding derived classes in ./src/welcome_dlg.hh and./src/welcome_dlg.cc

#ifndef _WELCOME_DLG_GLADE_HH
#  define _WELCOME_DLG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/label.h>
#include <gtkmm/image.h>
#include <gtkmm/fixed.h>
#include <gtkmm/entry.h>
#include <gtkmm/button.h>
#include <gtkmm/box.h>

class welcome_dlg_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * welcome_dlg;
        class Gtk::Label * label7;
        class Gtk::Image * Tux_image;
        class Gtk::Fixed * fixed7;
        class Gtk::Entry * init_password_edit_box;
        class Gtk::Label * init_password_label;
        class Gtk::Label * repeat_password_label;
        class Gtk::Entry * repeat_password_edit_box;
        class Gtk::Label * secret_question_label;
        class Gtk::Label * secret_answer_label;
        class Gtk::Entry * secret_q_edit_box;
        class Gtk::Entry * secret_a_edit_box;
        class Gtk::Button * welcome_next_button;
        class Gtk::Label * welcome_hint_label;
        class Gtk::Fixed * fixed6;
        class Gtk::VBox * vbox2;
protected:
        
        welcome_dlg_glade();
        
        ~welcome_dlg_glade();
private:
        virtual bool on_repeat_password_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual bool on_secret_a_edit_box_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_welcome_next_button_clicked() = 0;
        virtual bool on_welcome_dlg_delete_event(GdkEventAny *ev) = 0;
};
#endif
